### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by misan** [whosawhatsis/RepRap-Wallace#5]
WARNING: Can't open import file `/Applications/gregs/gregs_accessible_wade-wildseyed_mount.stl'.

Not sure it matters, but just in case.

**Comment by whosawhatsis** [comment]
That was just to visualize the placement of the extruder. It's not necessary at all, but you can get the STL here: http://www.thingiverse.com/thing:8252

**Comment by misan** [comment]
Ok. Thanks.
