### ISSUE TITLE
Split up OpenSCAD script into modules

### ISSUE THREAD

**Issue by ace-dent** [whosawhatsis/RepRap-Wallace#8]
Howdy!

Would you be interested in splitting up your monolithic script into separate parts?
I'm keen to do this and add ThingDoc support. At this early stage would rather see this in the canonical version, rather just forking it...

Happy to help / discuss :)
Andrew

**Comment by whosawhatsis** [comment]
I haven't looked into thingdoc, but it sounds like something I would like to support. As for splitting up wallace.scad, see here: https://plus.google.com/u/0/105535247347788377245/posts/3QCRU6MjbrA

**Comment by ace-dent** [comment]
Ok, no problems.
However, why not do both?
If you keep your main script as the canonical source (active development), I'm happy to maintain copying modules out to the individual scripts and keep them closely in sync. Once development settles down, I think this would be quite manageable.

Either way, happy to help out.

**Comment by whosawhatsis** [comment]
Maintaining two copies of everything will only cause confusion. Even if they remain synchronized in the repo all the time, other people trying to make edits will try to edit the wrong copy and be confused when nothing happens.

**Comment by ace-dent** [comment]
Yes, ok. The point of splitting was really for ThingDoc integration, which can be achieved now with the place-holder/ rendering scripts.
